# Transformación de variables en SKlearn
## 1. Objetivo

Familiarizarse con los conceptos de transformación de variables.

## Datos de Melb Houses
* Suburb: Suburb
* Address: Address
* Rooms: Number of rooms
* Price: Price in Australian dollars
* Method:
  * S - property sold;
  * SP - property sold prior;
  * PI - property passed in;
  * PN - sold prior not disclosed;
  * SN - sold not disclosed;
  * NB - no bid;
  * VB - vendor bid;
  * W - withdrawn prior to auction;
  * SA - sold after auction;
  * SS - sold after auction price not disclosed.
  * N/A - price or highest bid not available.

* Type:
  * br - bedroom(s);
  * h - house,cottage,villa, semi,terrace;
  * u - unit, duplex;
  * t - townhouse;
  * dev site - development site;
  * res - other residential.

* SellerG: Real Estate Agent

* Date: Date sold

* Distance: Distance from CBD in Kilometres
* Regionname: General Region (West, North West, North, North east …etc)
* Propertycount: Number of properties that exist in the suburb.
* Bedroom2 : Scraped # of Bedrooms (from different source)
* Bathroom: Number of Bathrooms
* Car: Number of carspots
* Landsize: Land Size in Metres
* BuildingArea: Building Size in Metres
* YearBuilt: Year the house was built
* CouncilArea: Governing council for the area
* Lattitude: Self explanitory
* Longtitude: Self explanitory

* Melb Data: https://www.kaggle.com/code/dansbecker/handling-missing-values/data?select=melb_data.csv
* Sklearn Cheat Sheet from Datacamp: https://media.datacamp.com/legacy/image/upload/v1676302389/Marketing/Blog/Scikit-Learn_Cheat_Sheet.pdf

## 2. Librerias de trabajo

In [1]:
# Instala libreria Pandas si no la tenemos
#pip install pandas seaborn scikit-learn -y

In [2]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# importa clase de Python para instanciar el modelo KNN
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

## 3. Lectura de datos

Primero nos encargaremos de leer los datos, indicando a Python donde se encuentra la carpeta que contiene los datos y los nombres de los archivos relevantes para el análisis.

In [3]:
#  Indicamos la ruta a la carpeta de de tu computadora 
# donde se ubican los datos del E-commerce
# Ejemplo: "C:\Usuarios\[tu nombre]\Descargas"

DATA_PATH="/Users/cesar/sandbox/ai_programming_foundations/data"

Ahora procederemos a definir una variable que indique el nombre del archivo junto con su extensión (por ejemplo, `.csv`):

In [4]:
FILE_DATA_PATH = "melb_data.csv"

Echaremos mano de la utilidad `os.path.join` de Python que indicar rutas en tu computadora donde se ubican archivos, así Pandas encontrá los archivos de datos.


**Ejemplo**

A continuación mostraremos un ejemplo leyendo el archivo `melb_data.csv`:

In [5]:
# Ejemplo
print(f"Ruta del archivo: {FILE_DATA_PATH}")
print(os.path.join(DATA_PATH, FILE_DATA_PATH))

Ruta del archivo: melb_data.csv
/Users/cesar/sandbox/ai_programming_foundations/data/melb_data.csv

In [6]:
# Leemos con pandas
df = pd.read_csv(
    os.path.join(DATA_PATH, FILE_DATA_PATH)
    )

In [7]:
df.head(10)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,03/12/16,2.5,3067,...,1,1.0,202,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,04/02/16,2.5,3067,...,1,0.0,156,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,04/03/17,2.5,3067,...,2,0.0,134,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019
3,Abbotsford,40 Federation La,3,h,850000,PI,Biggin,04/03/17,2.5,3067,...,2,1.0,94,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019
4,Abbotsford,55a Park St,4,h,1600000,VB,Nelson,04/06/16,2.5,3067,...,1,2.0,120,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019
5,Abbotsford,129 Charles St,2,h,941000,S,Jellis,07/05/16,2.5,3067,...,1,0.0,181,NaN,NaN,Yarra,-37.8041,144.9953,Northern Metropolitan,4019
6,Abbotsford,124 Yarra St,3,h,1876000,S,Nelson,07/05/16,2.5,3067,...,2,0.0,245,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019
7,Abbotsford,98 Charles St,2,h,1636000,S,Nelson,08/10/16,2.5,3067,...,1,2.0,256,107.0,1890.0,Yarra,-37.8060,144.9954,Northern Metropolitan,4019
8,Abbotsford,6/241 Nicholson St,1,u,300000,S,Biggin,08/10/16,2.5,3067,...,1,1.0,0,NaN,NaN,Yarra,-37.8008,144.9973,Northern Metropolitan,4019
9,Abbotsford,10 Valiant St,2,h,1097000,S,Biggin,08/10/16,2.5,3067,...,1,2.0,220,75.0,1900.0,Yarra,-37.8010,144.9989,Northern Metropolitan,4019

Recordemos cuales son las columnas

In [8]:
# formato de columnas en crudo
raw_columns = list(df.columns)
raw_columns

['Suburb',
 'Address',
 'Rooms',
 'Type',
 'Price',
 'Method',
 'SellerG',
 'Date',
 'Distance',
 'Postcode',
 'Bedroom2',
 'Bathroom',
 'Car',
 'Landsize',
 'BuildingArea',
 'YearBuilt',
 'CouncilArea',
 'Lattitude',
 'Longtitude',
 'Regionname',
 'Propertycount']

Revisemo las información de los datos:

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  int64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64
 10  Bedroom2       13580 non-null  int64
 11  Bathroom       13580 non-null  int64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  int64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  int64
dtypes: float64(6), int64(7), object(8)
memory usage: 2.2+ MB

In [10]:
# Columnas para predecir
features = [
    'Rooms', 
    'BuildingArea',
    'Landsize',
    'Distance',
    'Bathroom',
    ]

# columna objectivo a predecir
target = ['Price']

In [11]:
df.filter(features+target).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rooms         13580 non-null  int64
 1   BuildingArea  7130 non-null   float64
 2   Landsize      13580 non-null  int64
 3   Distance      13580 non-null  float64
 4   Bathroom      13580 non-null  int64
 5   Price         13580 non-null  int64
dtypes: float64(2), int64(4)
memory usage: 636.7 KB

**Dividimos al conjunto en entrenamiento y prueba**

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    df[features].fillna(0),
    df[target],
    test_size=0.2,
    random_state=210
)

In [13]:
X_test.sample(20)

       Rooms  BuildingArea  Landsize  Distance  Bathroom
13242      5           0.0       654      18.8         3
10442      4           0.0       423       5.3         3
5480       3           0.0       174      11.4         1
4851       2           0.0        98       4.5         1
2582       2         118.0       223       3.5         1
4749       3         153.0       225       3.8         2
3338       3           0.0       698      13.0         1
4419       2           0.0       367       5.5         1
11455      4         148.0       558      10.4         1
6466       3         111.0       355      14.9         1
3468       3           0.0       254      12.8         1
10491      3           0.0       835      19.9         1
5278       2          76.0      2740       2.6         2
585        3         167.0       260       9.2         2
3809       3         106.0       246       7.4         2
7787       4         185.0       872      13.9         2
7170       3           0.0       703      11.8         1
8052       3           0.0      2787       9.2         3
5913       2           0.0       151       9.7         1
1113       3         120.0       426      11.2         1

## 4. Ingeniería de características

La ingeniería de características es un proceso en el que se seleccionan, transforman o crean nuevas variables a partir de los datos originales para mejorar el rendimiento de un modelo de aprendizaje automático.

En el contexto de un problema de aprendizaje supervisado de regresión, la ingeniería de características implica buscar y seleccionar las variables que más influyen en la variable objetivo (la variable que se quiere predecir), transformar las variables para que se ajusten mejor al modelo, o incluso crear nuevas variables a partir de las variables existentes.

Por ejemplo, si se quiere predecir el precio de una casa en función de su tamaño y ubicación, se podría ingeniar nuevas características como la distancia a las escuelas, la cantidad de tiendas cercanas, la edad del vecindario, etc. También se podrían transformar las variables existentes, como la altura del techo o el número de habitaciones, para que se ajusten mejor al modelo.

En términos muy generales, las técnicas para crear nuevas variables para un modelo de aprendizaje de máquina se pueden agrupar en torno a cuatro categorías:

**Creación de características:** Se refiere a definir nuevas variables con la información disponible, tipicamente implica operar los datos actuales con operaciones básicas como operaciones como suma, resta, multiplicación o división entre ellas. En algunos casos es común crear cocientes de variables. Por ejemplo, se puede calcular el precio promedio de la venta de una mercancia en una semana particualr para predecir cuanto se vendera en la siguiente. Generalmente requieren aplicar conocomientos del negocio para que las variables generadas tengan sentido.

**Transformación de características:** Relativa a aplicar una transformacion sobre una variable específica con el objetivo de mejorar el desempeño del modelo. En este caso se puede incluir transformaciones que buscan poner a las variables en la misma escala numérica; esto es importante pues comunmente muchas de las variables de un modelo se encuentra en unidades dispares (por ejemplo, miles de pesos y milimetros), lo que puede dificultar la interpretabilidad de los resultados de un modelo y generar inestabilidad numérica en los métodos de optimización para minimizar la función de pérdida.

**Extracción de características:** Se refiere al proceso de transformación de datos sin procesar en características numéricas que se pueden procesar mientras se preserva la información en el conjunto de datos original. Produce mejores resultados que aplicar el aprendizaje automático directamente a los datos sin procesar. Un ejemplo de esto es proyectar el espacio de características en un espacio vectorial de menor dimension, con propiedades deseables como la independencia lineal u ortohonalidad, o bien con menor dimensión y conservando cierto nivel de información estadística, como el Análisis de Componentes Principales (ver por ejemplo https://www.youtube.com/watch?v=n7npKX5zIWI).

**Selección de características:** se refiere a los algoritmos de selección, análisis y categorización de características por importancia para predecir con un modelo. Normalmente tener muchas variables puede afectar las predicciones de un modelo, pues puede contier características redundantes y que por el problema de la maldición de la dimensionalidad complicar el proceso de inferencia de parámetros adecuados para un modelo.


### 4.1 Creación de características

### 4.1.1 Variables polinómicas e interacciones

En muchos de los casos de los problema de aprendizaje, las variables interactuan entre si en formas inexperadas y bajo comportamientos no lineales que no son fáciles de capturar.

Estas interacciones se pueden identificar y modelar mediante un algoritmos sufiencientemente flexibles para capturar dicha complejidad, pero también se pueden aproximar con transformaciones resultado de elevar las variables de entrada a una potencia como si se tratase de una expresión de un polinomio multivariado de un grado específico.

Por ejemplo, si se tiene variable $x_1, x_2, x_3$ nos podría interesar las variables $x_1 x_2, x_2 x_3, x_1 x_3, x_1^2, x_2^2, x_3^2$, donde las multiplicaciones $x_i x_j$ modelan el efecto de interacción de ambos factores. Estos son elementos de un polinomio de segundo orden, pero pueden considerarse potencias de órdenes mayores.

Cabe destacar que considerar un grado alto de un polinomio aumenta drásticamente el número de características de entrada y puede no necesariamente incrementar la información estadística para mejorar el desempeño del modelo como predictor.

En Sklearn se pueden estimar fácilmente este tipo de transformaciones con la clase `PolynomialFeatures`. El proceso a seguir con un transformador de este estilo es el siguiente:

* Ajustar el transformador `.fit` en el **conjunto de entrenamiento**
* Obtener los datos transformados `.predict` para el conjunto de entrenamiento y prueba,
* Continuar con el flujo de ajuste del modelo.

**Nota:** Los transformadores **siempre** deben ajustarse en el conjunto de entrenamiento, dado que usar el conjunto de prueba o en los datos originales completos puede producir fuga de datos.

In [14]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)

In [15]:
poly.fit(X_train[features])

PolynomialFeatures()

In [16]:
X_train_poly = pd.DataFrame(
    poly.transform(X_train[features]),
    columns=poly.get_feature_names_out(features)
    )

X_test_poly = pd.DataFrame(
    poly.transform(X_test[features]),
    columns=poly.get_feature_names_out(features)
    )

Podemos examinar las variables recién creadas, donde encontramos potencias de las variables y multiplicaciones cruzadas de las mismas hasta en grado 2:

In [17]:
X_train_poly.transpose()

,0,1,2,3,4,5,6,7,8,9,...,10854,10855,10856,10857,10858,10859,10860,10861,10862,10863
1,1.00,1.00,1.00,1.00,1.00,1.0,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Rooms,4.00,3.00,2.00,3.00,2.00,4.0,3.00,1.00,3.00,3.00,...,3.00,3.00,4.00,4.00,4.00,5.00,3.00,3.00,3.00,3.00
BuildingArea,364.00,18.00,105.00,0.00,92.00,0.0,148.00,0.00,228.00,0.00,...,0.00,131.00,249.00,4.00,220.00,222.00,0.00,140.00,0.00,0.00
Landsize,508.00,616.00,288.00,620.00,114.00,1005.0,0.00,0.00,322.00,854.00,...,475.00,272.00,515.00,276.00,556.00,580.00,437.00,720.00,1157.00,650.00
Distance,19.60,9.40,6.50,11.20,17.90,18.0,10.30,12.10,6.40,9.20,...,3.50,4.40,7.80,7.80,7.50,10.60,11.20,20.80,13.90,1.90
Bathroom,3.00,1.00,1.00,1.00,1.00,1.0,2.00,1.00,2.00,1.00,...,1.00,1.00,3.00,2.00,2.00,2.00,1.00,1.00,1.00,2.00
Rooms^2,16.00,9.00,4.00,9.00,4.00,16.0,9.00,1.00,9.00,9.00,...,9.00,9.00,16.00,16.00,16.00,25.00,9.00,9.00,9.00,9.00
Rooms BuildingArea,1456.00,54.00,210.00,0.00,184.00,0.0,444.00,0.00,684.00,0.00,...,0.00,393.00,996.00,16.00,880.00,1110.00,0.00,420.00,0.00,0.00
Rooms Landsize,2032.00,1848.00,576.00,1860.00,228.00,4020.0,0.00,0.00,966.00,2562.00,...,1425.00,816.00,2060.00,1104.00,2224.00,2900.00,1311.00,2160.00,3471.00,1950.00
Rooms Distance,78.40,28.20,13.00,33.60,35.80,72.0,30.90,12.10,19.20,27.60,...,10.50,13.20,31.20,31.20,30.00,53.00,33.60,62.40,41.70,5.70
Rooms Bathroom,12.00,3.00,2.00,3.00,2.00,4.0,6.00,1.00,6.00,3.00,...,3.00,3.00,12.00,8.00,8.00,10.00,3.00,3.00,3.00,6.00
BuildingArea^2,132496.00,324.00,11025.00,0.00,8464.00,0.0,21904.00,0.00,51984.00,0.00,...,0.00,17161.00,62001.00,16.00,48400.00,49284.00,0.00,19600.00,0.00,0.00
BuildingArea Landsize,184912.00,11088.00,30240.00,0.00,10488.00,0.0,0.00,0.00,73416.00,0.00,...,0.00,35632.00,128235.00,1104.00,122320.00,128760.00,0.00,100800.00,0.00,0.00
BuildingArea Distance,7134.40,169.20,682.50,0.00,1646.80,0.0,1524.40,0.00,1459.20,0.00,...,0.00,576.40,1942.20,31.20,1650.00,2353.20,0.00,2912.00,0.00,0.00
BuildingArea Bathroom,1092.00,18.00,105.00,0.00,92.00,0.0,296.00,0.00,456.00,0.00,...,0.00,131.00,747.00,8.00,440.00,444.00,0.00,140.00,0.00,0.00
Landsize^2,258064.00,379456.00,82944.00,384400.00,12996.00,1010025.0,0.00,0.00,103684.00,729316.00,...,225625.00,73984.00,265225.00,76176.00,309136.00,336400.00,190969.00,518400.00,1338649.00,422500.00
Landsize Distance,9956.80,5790.40,1872.00,6944.00,2040.60,18090.0,0.00,0.00,2060.80,7856.80,...,1662.50,1196.80,4017.00,2152.80,4170.00,6148.00,4894.40,14976.00,16082.30,1235.00
Landsize Bathroom,1524.00,616.00,288.00,620.00,114.00,1005.0,0.00,0.00,644.00,854.00,...,475.00,272.00,1545.00,552.00,1112.00,1160.00,437.00,720.00,1157.00,1300.00
Distance^2,384.16,88.36,42.25,125.44,320.41,324.0,106.09,146.41,40.96,84.64,...,12.25,19.36,60.84,60.84,56.25,112.36,125.44,432.64,193.21,3.61
Distance Bathroom,58.80,9.40,6.50,11.20,17.90,18.0,20.60,12.10,12.80,9.20,...,3.50,4.40,23.40,15.60,15.00,21.20,11.20,20.80,13.90,3.80
Bathroom^2,9.00,1.00,1.00,1.00,1.00,1.0,4.00,1.00,4.00,1.00,...,1.00,1.00,9.00,4.00,4.00,4.00,1.00,1.00,1.00,4.00

Con este procesamiento, ya estamos en condiciones de entrenar el modelo junto con las nuevas características:

In [18]:
# Instancia el modelo KNN para 30 vecinos
model_poly = KNeighborsRegressor(n_neighbors=5)

# Ajusta el modelo con los datos de prueba
model_poly.fit(X_train_poly,y_train)

y_train_pred = model_poly.predict(X_train_poly)
y_test_pred = model_poly.predict(X_test_poly)

# error en conjunto de entrenamiento y prueba
error_train = root_mean_squared_error(y_train, y_train_pred)
error_test = root_mean_squared_error(y_test, y_test_pred)

# errores
print("Error RSME en train:", round(error_train,2) )
print("Error RSME en test:", round(error_test,2) )

Error RSME en train: 416935.34
Error RSME en test: 552500.55

**Pregunta**

* El modelo presenta un error sustancialmente más alto en el conjunto de entrenamiento que en el de prueba ¿está subajustando o sobreajustando?
* Considerando lo anterior, ¿qué consecuencias tendria usar con un modelo con estas características para las predicciones de los precios de viviendas??

**Pipeline de Sklearn**

Una de las funcionalidades más atractivas de SKlearn es la utilidad `Pipeline`, que permite encadenar una serie de transformaciones sobre los datos y entrenar modelos de forma fácil.

Esencialmente funciona creando un lista de tuplas que indica el nombre de las transformaciones o modelos a aplicar junto son su nombre, que describe los pasos que se usaran en el procesamiento y posteriormente se puede ajustar sobre los datos de entrenamiento para predecir sin tener que hacer ajustes manuales como en el ejemplo anterior.

El siguiente ejemplo ejecuta la creación de variables polinomicas con las columnas del clima, hasta grado 2, para posteriormente entrenar un modelo KNN de 5 vecinos:

In [19]:
from sklearn.pipeline import Pipeline

# Crea lista de tuplas con nombre de transformaciones/modelo
# junto con sus nombres
estimators = [
    # Creacion de variables polinomicas
    ('polinomical_features', PolynomialFeatures(degree=2)),
    # Modelo KNN de 5 vecinos mas proximos
    ('knn_model', KNeighborsRegressor(n_neighbors=5))
    ]

# comunica al pipeline la lista en el orden que se deben aplicar
# estos pasos
pipe = Pipeline(steps=estimators)

In [20]:
# Realiza la transformacion de los datos y el ajuste del modelo
pipe.fit(X_train[features], y_train)

y_train_pred = pipe.predict(X_train[features])
y_test_pred = pipe.predict(X_test[features])

# error en conjunto de entrenamiento y prueba
error_train = root_mean_squared_error(y_train, y_train_pred)
error_test = root_mean_squared_error(y_test, y_test_pred)

# errores
print("Error RSME en train:", round(error_train,2) )
print("Error RSME en test:", round(error_test,2) )

Error RSME en train: 416935.36
Error RSME en test: 552500.55

### 4.1.2 Normalización de la escala de variables

Uno de los problemas más frecuentes es la disparidad en la escala de variables cuando se construye un modelo; por ejemplo, algunas de las unidades de las variables pueden estar en miles de pesos y otras en milimetros.

En general, esto perjudica la interpretabilidad de los modelos pero también induce inestabilidad numérica en los algoritmos que aproximan las soluciones de los cálculos necesarios para ajustar un modelo, por lo que es deseable generar transformaciones que generen datos en el mismo orden de magnitud.

Algunas de las transformaciones más populares son:

**Escalamiento estándar o z-score:** Es una transformación que resta la media de los datos y los divide entre su desviación estándar, es decir:

  $$ \frac{x - \mu_x }{\sigma_x}$$

  Genera valores positivos y negativos centrados en cero.

  **Escalamiento Min-Max:** Se trata de una transformación que pone lleva los datos a valores al intervalo $(0, 1)$, restando a todos los valores el minimo de entre ellos y dividiendo entre la resta del maximo menos el mínimo es decir:

  $$ \frac{x - \min x }{\max x - \min x }$$


En Sklearn estos son accesibles con las clases `StandardScaler` y `MinMaxScaler`:

In [21]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [22]:
# Ejemplo de ajuste y transformacion con escalamiento estandar
standard_scaler = StandardScaler()

pd.DataFrame(
standard_scaler.fit_transform(X_train[features]),
columns=features
)

          Rooms  BuildingArea  Landsize  Distance  Bathroom
0      1.119352      0.635507 -0.012745  1.612322  2.110989
1      0.066300     -0.143541  0.012099 -0.128230 -0.768331
2     -0.986751      0.052347 -0.063351 -0.623093 -0.768331
3      0.066300     -0.184070  0.013019  0.178926 -0.768331
4     -0.986751      0.023076 -0.103375  1.322230 -0.768331
...         ...           ...       ...       ...       ...
10859  2.172404      0.315782  0.003818  0.076541  0.671329
10860  0.066300     -0.184070 -0.029076  0.178926 -0.768331
10861  0.066300      0.131152  0.036021  1.817092 -0.768331
10862  0.066300     -0.184070  0.136544  0.639660 -0.768331
10863  0.066300     -0.184070  0.019919 -1.408047  0.671329

[10864 rows x 5 columns]

In [23]:
# Ejemplo de ajuste y transformacion con escalamiento min-max
min_max_scaler = MinMaxScaler()

pd.DataFrame(
min_max_scaler.fit_transform(X_train[features]),
columns=features
)

          Rooms  BuildingArea  Landsize  Distance  Bathroom
0      0.333333      0.008177  0.001173  0.407484     0.375
1      0.222222      0.000404  0.001423  0.195426     0.125
2      0.111111      0.002359  0.000665  0.135135     0.125
3      0.222222      0.000000  0.001432  0.232848     0.125
4      0.111111      0.002067  0.000263  0.372141     0.125
...         ...           ...       ...       ...       ...
10859  0.444444      0.004987  0.001339  0.220374     0.250
10860  0.222222      0.000000  0.001009  0.232848     0.125
10861  0.222222      0.003145  0.001663  0.432432     0.125
10862  0.222222      0.000000  0.002672  0.288981     0.125
10863  0.222222      0.000000  0.001501  0.039501     0.250

[10864 rows x 5 columns]

Estas transformaciones se puueden combinar con otras usando `Pipeline`, por ejemplo los siguientes son ejemplos de la creacions de variables polinomicas para entrenar un modelo KNN, escalando primero las variables numéricas con los métodos recién descrito:

In [24]:
# Crea lista de tuplas con nombre de transformaciones/modelo
# junto con sus nombres
estimators_standar_poly = [
    # escalamiento estandar
    ('min_max_scaler', StandardScaler()),
    # Creacion de variables polinomicas
    ('polinomical_features', PolynomialFeatures(degree=2)),
    # Modelo KNN de 5 vecinos mas proximos
    ('knn_model', KNeighborsRegressor(n_neighbors=5))
    ]

# comunica al pipeline la lista en el orden que se deben aplicar
# estos pasos
pipe_standard_poly = Pipeline(steps=estimators_standar_poly)

# Realiza la transformacion de los datos y el ajuste del modelo
pipe_standard_poly.fit(X_train[features], y_train)

y_train_pred = pipe_standard_poly.predict(X_train[features])
y_test_pred = pipe_standard_poly.predict(X_test[features])

# error en conjunto de entrenamiento y prueba
error_train = root_mean_squared_error(y_train, y_train_pred)
error_test = root_mean_squared_error(y_test, y_test_pred)

# errores
print("Error RSME en train:", round(error_train,2) )
print("Error RSME en test:", round(error_test,2) )

Error RSME en train: 348419.51
Error RSME en test: 436650.68

In [25]:
# Crea lista de tuplas con nombre de transformaciones/modelo
# junto con sus nombres
estimators_min_max_poly = [
    # escalamiento min max
    ('min_max_scaler', MinMaxScaler()),
    # Creacion de variables polinomicas
    ('polinomical_features', PolynomialFeatures(degree=2)),
    # Modelo KNN de 5 vecinos mas proximos
    ('knn_model', KNeighborsRegressor(n_neighbors=5))
    ]

# comunica al pipeline la lista en el orden que se deben aplicar
# estos pasos
pipe_min_max_poly = Pipeline(steps=estimators_min_max_poly)

# Realiza la transformacion de los datos y el ajuste del modelo
pipe_min_max_poly.fit(X_train[features], y_train)

y_train_pred = pipe_min_max_poly.predict(X_train[features])
y_test_pred = pipe_min_max_poly.predict(X_test[features])

# error en conjunto de entrenamiento y prueba
error_train = root_mean_squared_error(y_train, y_train_pred)
error_test = root_mean_squared_error(y_test, y_test_pred)

# errores
print("Error RSME en train:", round(error_train,2) )
print("Error RSME en test:", round(error_test,2) )

Error RSME en train: 350523.47
Error RSME en test: 435725.42

### 4.1.3 Transformaciones a variables categóricas

Los algoritmos de machine learning solo pueden trabajar con representaciones numéricas, es decir, no interpretan directamente textos o variables categóricas por si mismos. Por ellos es necesario que permita convertir datos categóricos a variables numéricas (*encoding*)


Existen varios tipos de encoding de variables categóricas, entre los más populares:

* **Label Encoding:** Este método asigna un número a cada valor único en la variable categórica en función de su posición en una lista ordenada alfabéticamente. Por ejemplo, si tuvieramos una columna de estilos musicales (`j-pop`, `clasico`, `heavy metal`), el encoding resultante sería (`3`,`1`, `2`).
* **Ordinal Encoding:** Este método asigna un número a cada valor único en la variable categórica en función de su posición en una lista ordenada según su importancia o relevancia en el modelo. Es útil con variables que tienen una relación jerarquica que desea representarse (por ejemplo, si tenemos una variable que representa tamaños de autos `chico`, `mediado` y `grande`, estos se pueden representar como `1`,`2` y `3`).
* **Binary Encoding:** Este método convierte cada valor único en la variable categórica en un número binario y luego divide el número en columnas separadas para cada dígito binario.
* **One-Hot Encoding:** Este método crea una columna separada para cada valor único en la variable categórica y asigna un 1 o 0 a cada columna según si el valor está presente o no en la fila. Generalmente One-Hot encoding es mejor captando variaciones cuando existe variaciones importantes a lo largo de muchas categorias, sin embargo la cantidad de características incrementa sustancialmente y el tiempo del procesamiento para ajusta los modelos.

**Figura 1: Representación del One-Hot-Encoding**
![title](../images/one_hot_encoding.png)


Puede leerse más al respecto en la documentación de Sklearn: https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline.html

Cada método tiene sus propias ventajas y desventajas, y la elección del método adecuado depende del conjunto de datos y el modelo específicos que se estén utilizando.

Adicionalmente cada uno está disponible en Sklearn respectivamente a través de las siguientes clases:
* LabelEncoder,
* OrdinalEncoder,
* LabelBinarizer,
* OneHotEncoder,

In [26]:
from sklearn.preprocessing import (
    LabelEncoder,
    OrdinalEncoder,
    LabelBinarizer,
    OneHotEncoder
)

* **Label Encoding**

Un ejemplo de como aplicar label encoding se puede obtener con el campo `Regionname`, que como sabemos tiene varias zonas (`Northern Metropolitan`, `Western Metropolitan`, `Southern Metropolitan`, `Eastern Metropolitan`, `South-Eastern Metropolitan`, `Eastern Victoria`, `Northern Victoria` y  `Western Victoria`), que a través de `LabelEncoder` se representarían como 1,2, 0 y 3 (de acuerdo al orden alfabético).

In [27]:
le = LabelEncoder()
le.fit_transform(df['Regionname'])

array([2, 2, 2, ..., 6, 6, 6])

In [28]:
le.classes_

array(['Eastern Metropolitan', 'Eastern Victoria',
       'Northern Metropolitan', 'Northern Victoria',
       'South-Eastern Metropolitan', 'Southern Metropolitan',
       'Western Metropolitan', 'Western Victoria'], dtype=object)

* **Binary Encoding sobre functioning_day**

Como sabemos la variable `Distance` refleja la distancia de la vivienda en kilómetros desde el CBD. Podemos usarla para definir si esta se encuentra "cerca" (en un radio arbitarios de 5 kilometros) o "lejos" (más alla de 5 km).

 con la `LabelBinarizer` se puede transformar en valores numéricos para que 0 represente a `No` y 1 a `Yes`.

In [29]:
np.where(df['Distance']<=5, "cerca", "lejos")

array(['cerca', 'cerca', 'cerca', ..., 'lejos', 'lejos', 'lejos'],
      dtype='<U5')

In [30]:
df['distance_type'] = np.where(df['Distance']<=5, "cerca", "lejos")

In [31]:
# Instanciamos la clase para 
lb = LabelBinarizer()

lb.fit_transform(df['distance_type'])

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [32]:
lb.classes_

array(['cerca', 'lejos'], dtype='<U5')

* One Hot Encoding sobre `Type`:

Una forma de codificar a la columna Type es el one-hot encoding que generaria 4 columnas indicadoras del tipo de vivienda de la que se trata:

* br - bedroom(s);
* h - house,cottage,villa, semi,terrace;
* u - unit, duplex;
* t - townhouse;
* dev site - development site;
* res - other residential.

In [33]:
ohe = OneHotEncoder()

# ajusta el transformador para generar el encoding
transformed = ohe.fit(df[['Type']])


# Crea un dataframe para visualizar el resultado del encoding
pd.DataFrame(
    transformed.transform(df[['Type']]).toarray(),
    columns=transformed.categories_
)

         h    t    u
0      1.0  0.0  0.0
1      1.0  0.0  0.0
2      1.0  0.0  0.0
3      1.0  0.0  0.0
4      1.0  0.0  0.0
...    ...  ...  ...
13575  1.0  0.0  0.0
13576  1.0  0.0  0.0
13577  1.0  0.0  0.0
13578  1.0  0.0  0.0
13579  1.0  0.0  0.0

[13580 rows x 3 columns]

**Combinando procesamientos de variables numéricas y categóricas: Pipeline y ColumnTransformer**

Como se ha visto hasta aquí, las columnas categóricas reciben un procesamiento distinto que las variables numéricas. 

Afortunadamente SKlearn tiene un funcionalidad para combinar procesamientos de varios estilos a través de la clase `ColumnTransformer`, que en términos simples nos permite aplicar procesamientos a grupos de columnas nombradas en una lista y después unirlas con `Pipeline` para trabajar de manera amigable.

En el siguiente ejemplo, se entrena un modelo KNN basado en las columnas del clima (numéricas),
la hora (pensado como un valor numérica) y seasons (que tiene cuatro categorías).

In [34]:
# Importamos ColumnTransformer
from sklearn.compose import ColumnTransformer

In [35]:
# Define listas de columnas que van a emplearse en el modelado
num_features = [
    'Rooms', 
    'BuildingArea',
    'Landsize',
    'Distance',
    'Bathroom',
    'YearBuilt'
 ]

bin_cols = ['distance_type']

cat_cols = ['Regionname', 'Type']

# Lista que tiene todas los grupos de columnas
non_target_cols = num_features + bin_cols + cat_cols

target = ['Price']

In [36]:
non_target_cols

['Rooms',
 'BuildingArea',
 'Landsize',
 'Distance',
 'Bathroom',
 'YearBuilt',
 'distance_type',
 'Regionname',
 'Type']

In [37]:
df["distance_type"].unique()

array(['cerca', 'lejos'], dtype=object)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    df[non_target_cols].fillna(0),
    df[target],
    test_size=0.2,
    random_state=210
)

Ahora creamos dos pipelines para procesar a las variables numéricas y categóricas

In [39]:
# Pipeline para escalar con estandar z-score
numerical_pipe = Pipeline([
    ('standar_scaler', StandardScaler())
])

# Pipeline para aplicar one hot encoding
binary_pipe = Pipeline([
    ('one_hot', OneHotEncoder(handle_unknown='ignore'))
])

categorical_pipe = Pipeline([
    ('one_hot', OneHotEncoder(handle_unknown='ignore'))
])

Posteriormente combinamos los 2 pipelines con `ColumnTransformer`, indicando en una lista de columnas a cuales de las características va a procesar cada pipelines. Nota: remainder='passthrough' es un flag para que considere el resto de columnas que no son procesadas.

In [40]:
# Combina ambos procesos en columnas espeficadas en listas
pre_processor = ColumnTransformer([
    ('numerical', numerical_pipe, num_features),
    ('binary', binary_pipe, bin_cols),
    ('categorical', categorical_pipe, cat_cols),
], remainder='passthrough')

Este pre-procesamiento se puede incluir ahora en un pipeline con el ajuste de modelo:

In [41]:
# comunica al pipeline la lista en el orden que se deben aplicar
# estos pasos

pipe_standard_ohe = Pipeline([
    ('transform', pre_processor),
    ('model', KNeighborsRegressor(n_neighbors=5))
])

In [42]:
# Realiza la transformacion de los datos y el ajuste del modelo
pipe_standard_ohe.fit(X_train[non_target_cols], y_train)

y_train_pred = pipe_standard_ohe.predict(X_train[non_target_cols])
y_test_pred = pipe_standard_ohe.predict(X_test[non_target_cols])

# error en conjunto de entrenamiento y prueba
error_train = root_mean_squared_error(y_train, y_train_pred)
error_test = root_mean_squared_error(y_test, y_test_pred)

# errores
print("Error RSME en train:", round(error_train,2) )
print("Error RSME en test:", round(error_test,2) )

Error RSME en train: 292760.27
Error RSME en test: 355242.56

**Preguntas**

* ¿Existe una mejora en el entrenamiento del modelo?
* ¿Existe sub-ajuste o sobre ajuste del modelo?