# Classification wtih Tensorflow

In [11]:
#pip install tensorflow

In [1]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import pandas as pd
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [2]:
data = load_diabetes()

In [37]:
df = pd.read_csv("../data/pima_diabetes.csv")
print(df.shape)
df.describe()

(768, 9)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [38]:
df.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
486,1,139,62,41,480,40.7,0.536,21,0
640,0,102,86,17,105,29.3,0.695,27,0
284,2,108,80,0,0,27.0,0.259,52,1
613,6,105,80,28,0,32.5,0.878,26,0
701,6,125,78,31,0,27.6,0.565,49,1

In [39]:
target = ['outcome'] 
features = [
    'Insulin',
    'Glucose',
    'BloodPressure',
    'BMI',
    'Pregnancies',
    'DiabetesPedigreeFunction',
    'Age',
    'SkinThickness'
 ]

df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [41]:
X = df[features].values
y = df['Outcome'].values

# Split data into training and testing sets (80% / 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features for better convergence
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [42]:
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

count_classes = y_test.shape[1]
print(count_classes)

2

In [ ]:
# Define a simple feedforward neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')  # output layer for regression
])

# Compile the model (use MSE for regression tasks)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy', 
    metrics=['accuracy']
)

Epoch 1/100

/Users/cesar/sandbox/ai_programming_foundations/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

39/39 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.6564 - loss: 0.6409 - val_accuracy: 0.7273 - val_loss: 0.5777
Epoch 2/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5215 - val_accuracy: 0.7597 - val_loss: 0.5142
Epoch 3/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4663 - val_accuracy: 0.7468 - val_loss: 0.5162
Epoch 4/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4477 - val_accuracy: 0.7662 - val_loss: 0.5179
Epoch 5/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4419 - val_accuracy: 0.7727 - val_loss: 0.5269
Epoch 6/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4327 - val_accuracy: 0.7597 - val_loss: 0.5389
Epoch 7/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4262 - val_accuracy: 0.7403 - val_loss: 0.5398
Epoch 8/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4184 - val_accuracy: 0.7273 - val_loss: 0.5483
Epoch 9/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4152 - val_accuracy: 0.7403 - val_loss: 0.5438
Epoch 10/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4141 - val_accuracy: 0.7273 - val_loss: 0.5458
Epoch 11/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4064 - val_accuracy: 0.7338 - val_loss: 0.5481
Epoch 12/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4015 - val_accuracy: 0.7273 - val_loss: 0.5592
Epoch 13/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3979 - val_accuracy: 0.7273 - val_loss: 0.5624
Epoch 14/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3947 - val_accuracy: 0.7338 - val_loss: 0.5655
Epoch 15/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3918 - val_accuracy: 0.7143 - val_loss: 0.5686
Epoch 16/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3866 - val_accuracy: 0.7403 - val_loss: 0.5627
Epoch 17/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8306 - loss: 0.3802 - val_accuracy: 0.7273 - val_loss: 0.5902
Epoch 18/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3809 - val_accuracy: 0.7403 - val_loss: 0.5806
Epoch 19/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3766 - val_accuracy: 0.7338 - val_loss: 0.5831
Epoch 20/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3721 - val_accuracy: 0.7468 - val_loss: 0.5850
Epoch 21/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3678 - val_accuracy: 0.7273 - val_loss: 0.5953
Epoch 22/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8485 - loss: 0.3633 - val_accuracy: 0.7208 - val_loss: 0.6010
Epoch 23/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3638 - val_accuracy: 0.7468 - val_loss: 0.5895
Epoch 24/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3576 - val_accuracy: 0.7338 - val_loss: 0.6156
Epoch 25/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3532 - val_accuracy: 0.7143 - val_loss: 0.5930
Epoch 26/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3483 - val_accuracy: 0.7273 - val_loss: 0.6283
Epoch 27/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3443 - val_accuracy: 0.7078 - val_loss: 0.6090
Epoch 28/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3427 - val_accuracy: 0.7273 - val_loss: 0.6273
Epoch 29/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3425 - val_accuracy: 0.7338 - val_loss: 0.6296
Epoch 30/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3346 - val_accuracy: 0.7273 - val_loss: 0.6263
Epoch 31/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3271 - val_accuracy: 0.7078 - val_loss: 0.6336
Epoch 32/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3275 - val_accuracy: 0.7078 - val_loss: 0.6300
Epoch 33/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3261 - val_accuracy: 0.7143 - val_loss: 0.6263
Epoch 34/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.3175 - val_accuracy: 0.7208 - val_loss: 0.6446
Epoch 35/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3086 - val_accuracy: 0.7143 - val_loss: 0.6523
Epoch 36/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8713 - loss: 0.3112 - val_accuracy: 0.7273 - val_loss: 0.6743
Epoch 37/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8567 - loss: 0.3095 - val_accuracy: 0.7273 - val_loss: 0.6642
Epoch 38/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3039 - val_accuracy: 0.7143 - val_loss: 0.7065
Epoch 39/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2921 - val_accuracy: 0.7338 - val_loss: 0.6757
Epoch 40/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.2921 - val_accuracy: 0.7338 - val_loss: 0.6813
Epoch 41/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2882 - val_accuracy: 0.6753 - val_loss: 0.7405
Epoch 42/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2915 - val_accuracy: 0.7338 - val_loss: 0.7062
Epoch 43/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.2776 - val_accuracy: 0.7078 - val_loss: 0.6973
Epoch 44/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2797 - val_accuracy: 0.7273 - val_loss: 0.7054
Epoch 45/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2669 - val_accuracy: 0.7273 - val_loss: 0.7273
Epoch 46/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2703 - val_accuracy: 0.7078 - val_loss: 0.7243
Epoch 47/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2610 - val_accuracy: 0.7403 - val_loss: 0.7077
Epoch 48/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.2567 - val_accuracy: 0.7338 - val_loss: 0.7749
Epoch 49/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9039 - loss: 0.2541 - val_accuracy: 0.7208 - val_loss: 0.7784
Epoch 50/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.2461 - val_accuracy: 0.7338 - val_loss: 0.7753
Epoch 51/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2529 - val_accuracy: 0.7273 - val_loss: 0.7930
Epoch 52/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2320 - val_accuracy: 0.7078 - val_loss: 0.7845
Epoch 53/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9121 - loss: 0.2271 - val_accuracy: 0.7273 - val_loss: 0.8374
Epoch 54/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2346 - val_accuracy: 0.7078 - val_loss: 0.8266
Epoch 55/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2353 - val_accuracy: 0.7403 - val_loss: 0.8349
Epoch 56/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2184 - val_accuracy: 0.7338 - val_loss: 0.8530
Epoch 57/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9202 - loss: 0.2211 - val_accuracy: 0.7338 - val_loss: 0.8279
Epoch 58/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2261 - val_accuracy: 0.7338 - val_loss: 0.8625
Epoch 59/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2182 - val_accuracy: 0.6948 - val_loss: 0.8808
Epoch 60/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9332 - loss: 0.2029 - val_accuracy: 0.7078 - val_loss: 0.9136
Epoch 61/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.2012 - val_accuracy: 0.7143 - val_loss: 0.9000
Epoch 62/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1924 - val_accuracy: 0.7143 - val_loss: 0.9245
Epoch 63/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9300 - loss: 0.1968 - val_accuracy: 0.7078 - val_loss: 0.9193
Epoch 64/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1793 - val_accuracy: 0.7143 - val_loss: 0.9430
Epoch 65/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.1835 - val_accuracy: 0.7078 - val_loss: 0.9308
Epoch 66/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1768 - val_accuracy: 0.7338 - val_loss: 0.9313
Epoch 67/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9430 - loss: 0.1728 - val_accuracy: 0.7078 - val_loss: 0.9928
Epoch 68/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.1800 - val_accuracy: 0.7208 - val_loss: 1.0072
Epoch 69/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1632 - val_accuracy: 0.7273 - val_loss: 0.9723
Epoch 70/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1683 - val_accuracy: 0.6818 - val_loss: 1.0610
Epoch 71/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1642 - val_accuracy: 0.6883 - val_loss: 1.0050
Epoch 72/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1504 - val_accuracy: 0.7273 - val_loss: 0.9478
Epoch 73/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1603 - val_accuracy: 0.6948 - val_loss: 1.0557
Epoch 74/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9463 - loss: 0.1469 - val_accuracy: 0.6883 - val_loss: 1.0116
Epoch 75/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9495 - loss: 0.1411 - val_accuracy: 0.7013 - val_loss: 1.0856
Epoch 76/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1303 - val_accuracy: 0.7078 - val_loss: 1.1115
Epoch 77/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9528 - loss: 0.1341 - val_accuracy: 0.6883 - val_loss: 1.1830
Epoch 78/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.1335 - val_accuracy: 0.6883 - val_loss: 1.1253
Epoch 79/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1222 - val_accuracy: 0.7013 - val_loss: 1.1370
Epoch 80/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1265 - val_accuracy: 0.7013 - val_loss: 1.1454
Epoch 81/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1311 - val_accuracy: 0.6883 - val_loss: 1.1781
Epoch 82/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1203 - val_accuracy: 0.6883 - val_loss: 1.1739
Epoch 83/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.1070 - val_accuracy: 0.6948 - val_loss: 1.2237
Epoch 84/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1232 - val_accuracy: 0.7273 - val_loss: 1.2800
Epoch 85/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1395 - val_accuracy: 0.7078 - val_loss: 1.2087
Epoch 86/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1033 - val_accuracy: 0.7143 - val_loss: 1.2679
Epoch 87/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0979 - val_accuracy: 0.6948 - val_loss: 1.2339
Epoch 88/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0921 - val_accuracy: 0.6818 - val_loss: 1.3416
Epoch 89/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0957 - val_accuracy: 0.7273 - val_loss: 1.2647
Epoch 90/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0947 - val_accuracy: 0.6818 - val_loss: 1.3316
Epoch 91/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0945 - val_accuracy: 0.6948 - val_loss: 1.3419
Epoch 92/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9658 - loss: 0.0937 - val_accuracy: 0.6753 - val_loss: 1.3809
Epoch 93/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9674 - loss: 0.0891 - val_accuracy: 0.7013 - val_loss: 1.3705
Epoch 94/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0783 - val_accuracy: 0.6948 - val_loss: 1.3694
Epoch 95/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0775 - val_accuracy: 0.6688 - val_loss: 1.3944
Epoch 96/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0791 - val_accuracy: 0.6818 - val_loss: 1.4834
Epoch 97/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0671 - val_accuracy: 0.6883 - val_loss: 1.4119
Epoch 98/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0655 - val_accuracy: 0.7013 - val_loss: 1.3929
Epoch 99/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0625 - val_accuracy: 0.6753 - val_loss: 1.5382
Epoch 100/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0635 - val_accuracy: 0.6883 - val_loss: 1.4238

In [ ]:
model.summary()

In [ ]:
tf.keras.utils.plot_model(
    model, 
    to_file='model_architecture.png', 
    show_shapes=True, 
    show_layer_names=True,
    rankdir='TB' # 'TB' is top-to-bottom (default), 'LR' is left-to-right
)

In [ ]:

# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=16,
    verbose=1
)

In [ ]:

# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=16,
    verbose=1
)

In [44]:
# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {test_acc:.2f}")

Test accuracy: 0.69

In [45]:
# Optionally, make predictions
y_pred = model.predict(X_test)

print("Predictions example:", y_pred[:5].flatten())

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Predictions example: [0.99799925 0.00200075 0.99414647 0.00585346 0.98871017 0.01128973
 0.96810055 0.03189938 0.7702196  0.22978036]

In [46]:
pred_train= model.predict(X_train)
scores = model.evaluate(X_train, y_train, verbose=0)
print('Accuracy on training data: {}% \n Error on training data: {}'.format(scores[1], 1 - scores[1]))

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Accuracy on training data: 0.990227997303009%
 Error on training data: 0.009772002696990967

In [47]:
pred_test= model.predict(X_test)
scores2 = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy on test data: {}% \n Error on test data: {}'.format(scores2[1], 1 - scores2[1]))

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
Accuracy on test data: 0.6883116960525513%
 Error on test data: 0.31168830394744873

In [48]:
model.save('pima_diabetes_nn.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Review your model on:
* https://netron.app